### ISSUE TITLE
need some instructions

### ISSUE THREAD

**Issue by ml-and-ml** [MEDAL-IITB/Fast_WSI_Color_Norm#1]
Thank you for writing this software. 

I want to normalize a folder of svs files, based on one target, so I am using `op = 3`.
How do I make sure my GPU is being used because it seems to be very slow. 
Secondly, nothing gets saved to my output directoy.

Thanks!

**Comment by deepakanandece** [comment]
Can you send me the output on the terminal screen?

**Comment by zws123** [comment]
I have the same issue. Using tf CPU or GPU is the same. It is too slow. The image size is 147000 * 90000. Here is the result.
![WechatIMG1](https://user-images.githubusercontent.com/42369848/76406028-0eb98300-63c4-11ea-9797-093cf1195946.png)

**Comment by quanhao129611** [comment]
Why is this error reported?

To be normalized:['/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/data/210420-1 - 2019-12-26 17.33.27.ndpi'] using /home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/target_image/image_000001_10240_25600.png
________________________________________________________________________________________________

Target Stain Separation in progress:/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/target_image/image_000001_10240_25600.png,1280x1280
	 	 	 	 	 	 	 	 	 	 Time: 0
Image small enough...W estimation done using whole image
Number of white pixels sampled 1157850
Time elapsed : 0.209451
Traceback (most recent call last):
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/main.py", line 109, in <module>
    config=config)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Run_ColorNorm.py", line 320, in run_colornorm
    run_batch_colornorm(filenames, nstains, lamb, output_direc, level, background_correction, config)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Run_ColorNorm.py", line 131, in run_batch_colornorm
    Wi, i0 = Wfast(I, nstains, lamb, num_patches, patchsize, level, background_correction)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Estimate_W.py", line 109, in Wfast
    Wsource = W_sort(normalize_W(Wsource, nstains))
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Estimate_W.py", line 157, in W_sort
    r_b_2 = W[0][1] / W[2][1]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by quanhao129611** [comment]
> I have the same issue. Using tf CPU or GPU is the same. It is too slow. The image size is 147000 * 90000. Here is the result.
> ![WechatIMG1](https://user-images.githubusercontent.com/42369848/76406028-0eb98300-63c4-11ea-9797-093cf1195946.png)

My result is obviously incorrect. Have you encountered this problem?
source image
![image](https://user-images.githubusercontent.com/56860663/76698607-03c26380-66e0-11ea-9240-6e7586d8b963.png)
traget image
![image](https://user-images.githubusercontent.com/56860663/76698681-dde98e80-66e0-11ea-87bc-738064a655d0.png)


normalization
![image](https://user-images.githubusercontent.com/56860663/76698691-ee016e00-66e0-11ea-9b6b-768bea424908.png)

**Comment by zws123** [comment]
I also encountered some problems with this code. I have given up this method.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"quanhao129611"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月15日(星期天) 下午5:14
收件人:&nbsp;"MEDAL-IITB/Fast_WSI_Color_Norm"<Fast_WSI_Color_Norm@noreply.github.com&gt;;
抄送:&nbsp;"淡蓝色的阳光"<1006092713@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MEDAL-IITB/Fast_WSI_Color_Norm] need some instructions (#1)





  
I have the same issue. Using tf CPU or GPU is the same. It is too slow. The image size is 147000 * 90000. Here is the result.
 
  
My result is obviously incorrect. Have you encountered this problem?
 source image
 
 traget image
 
 
normalization

**Comment by ChenYuhang243** [comment]
Images normalized by this method are totally not useable. I wasted a lot of time on this. Strongly not recommend this method.

**Comment by dicklim** [comment]
> Images normalized by this method are totally not useable. I wasted a lot of time on this. Strongly not recommend this method.

The same. The op 4 and 5 is not given in the code. And the code is very hard to read. (From my opinion.)
