### ISSUE TITLE
Tried op = 2 and the result doesn't seem right

### ISSUE THREAD

**Issue by savourylie** [MEDAL-IITB/Fast_WSI_Color_Norm#7]
Target image
![Screen Shot 2019-12-27 at 5 01 21 PM](https://user-images.githubusercontent.com/5828418/71510885-5c494800-28cb-11ea-8a1b-0a4e6625d24d.png)

Source image
![Screen Shot 2019-12-27 at 5 01 35 PM](https://user-images.githubusercontent.com/5828418/71510920-71be7200-28cb-11ea-95ec-e8d9c8ad744e.png)

Result image
![Screen Shot 2019-12-27 at 5 01 54 PM](https://user-images.githubusercontent.com/5828418/71510929-77b45300-28cb-11ea-994b-2c279efe7af4.png)

Would love to know if this result is expected?

**Comment by quanhao129611** [comment]
Why do I get this error when I run op = 2, have you encountered this?

To be normalized:['/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/data/210420-1 - 2019-12-26 17.33.27.ndpi'] using /home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/target_image/image_000001_10240_25600.png
________________________________________________________________________________________________

Target Stain Separation in progress:/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/target_image/image_000001_10240_25600.png,1280x1280
	 	 	 	 	 	 	 	 	 	 Time: 0
Image small enough...W estimation done using whole image
Number of white pixels sampled 1157850
Time elapsed : 0.209451
Traceback (most recent call last):
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/main.py", line 109, in <module>
    config=config)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Run_ColorNorm.py", line 320, in run_colornorm
    run_batch_colornorm(filenames, nstains, lamb, output_direc, level, background_correction, config)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Run_ColorNorm.py", line 131, in run_batch_colornorm
    Wi, i0 = Wfast(I, nstains, lamb, num_patches, patchsize, level, background_correction)
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Estimate_W.py", line 109, in Wfast
    Wsource = W_sort(normalize_W(Wsource, nstains))
  File "/home/omnisky/tmp/quanhao/Fast_WSI_Color_Norm-master/Estimate_W.py", line 157, in W_sort
    r_b_2 = W[0][1] / W[2][1]
IndexError: index 1 is out of bounds for axis 0 with size 1
